run:
  timeout: 5m
  tests: false
  modules-download-mode: vendor
linters:
  enable:
    - cyclop
    - decorder
    - dupl
    - gocognit
    - godot
    - gosec
    - grouper
    - ifshort
    - revive
    - wrapcheck
linters-settings:
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: false
  gosec:
    exclude-generated: true
  grouper:
    const-require-single-const: true
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: true
    type-require-single-type: true
    type-require-grouping: true
    var-require-single-var: true
    var-require-grouping: true
  revive:
    rules:
      - name: exported
      - name: context-as-argument
  wrapcheck:
    ignoreSigRegexps: []
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
