// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: api/protobuf/generator.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Run struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Run) Reset() {
	*x = Run{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0}
}

type Run_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *Run_Request_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Values  *Run_Request_Values  `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *Run_Request) Reset() {
	*x = Run_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Request) ProtoMessage() {}

func (x *Run_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Request.ProtoReflect.Descriptor instead.
func (*Run_Request) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Run_Request) GetOptions() *Run_Request_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Run_Request) GetValues() *Run_Request_Values {
	if x != nil {
		return x.Values
	}
	return nil
}

type Run_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generated []string `protobuf:"bytes,1,rep,name=generated,proto3" json:"generated,omitempty"`
}

func (x *Run_Response) Reset() {
	*x = Run_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Response) ProtoMessage() {}

func (x *Run_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Response.ProtoReflect.Descriptor instead.
func (*Run_Response) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Run_Response) GetGenerated() []string {
	if x != nil {
		return x.Generated
	}
	return nil
}

type Run_Request_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Override         bool   `protobuf:"varint,1,opt,name=override,proto3" json:"override,omitempty"`
	WorkingDirectory string `protobuf:"bytes,2,opt,name=workingDirectory,proto3" json:"workingDirectory,omitempty"`
}

func (x *Run_Request_Options) Reset() {
	*x = Run_Request_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Request_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Request_Options) ProtoMessage() {}

func (x *Run_Request_Options) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Request_Options.ProtoReflect.Descriptor instead.
func (*Run_Request_Options) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Run_Request_Options) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

func (x *Run_Request_Options) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

type Run_Request_Values struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Golang      *Run_Request_Values_Golang      `protobuf:"bytes,1,opt,name=golang,proto3" json:"golang,omitempty"`
	Application *Run_Request_Values_Application `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
}

func (x *Run_Request_Values) Reset() {
	*x = Run_Request_Values{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Request_Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Request_Values) ProtoMessage() {}

func (x *Run_Request_Values) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Request_Values.ProtoReflect.Descriptor instead.
func (*Run_Request_Values) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Run_Request_Values) GetGolang() *Run_Request_Values_Golang {
	if x != nil {
		return x.Golang
	}
	return nil
}

func (x *Run_Request_Values) GetApplication() *Run_Request_Values_Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type Run_Request_Values_Golang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module  string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Run_Request_Values_Golang) Reset() {
	*x = Run_Request_Values_Golang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Request_Values_Golang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Request_Values_Golang) ProtoMessage() {}

func (x *Run_Request_Values_Golang) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Request_Values_Golang.ProtoReflect.Descriptor instead.
func (*Run_Request_Values_Golang) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *Run_Request_Values_Golang) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Run_Request_Values_Golang) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Run_Request_Values_Application struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Run_Request_Values_Application) Reset() {
	*x = Run_Request_Values_Application{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_generator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Run_Request_Values_Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_Request_Values_Application) ProtoMessage() {}

func (x *Run_Request_Values_Application) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_generator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_Request_Values_Application.ProtoReflect.Descriptor instead.
func (*Run_Request_Values_Application) Descriptor() ([]byte, []int) {
	return file_api_protobuf_generator_proto_rawDescGZIP(), []int{0, 0, 1, 1}
}

func (x *Run_Request_Values_Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Run_Request_Values_Application) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_protobuf_generator_proto protoreflect.FileDescriptor

var file_api_protobuf_generator_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xa2, 0x04, 0x0a,
	0x03, 0x52, 0x75, 0x6e, 0x1a, 0xf0, 0x03, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x51, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x2a,
	0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x9a, 0x02, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x2e, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x52, 0x06,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x4e, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3a, 0x0a, 0x06, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x1a, 0x43, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x32, 0x49, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3c,
	0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_protobuf_generator_proto_rawDescOnce sync.Once
	file_api_protobuf_generator_proto_rawDescData = file_api_protobuf_generator_proto_rawDesc
)

func file_api_protobuf_generator_proto_rawDescGZIP() []byte {
	file_api_protobuf_generator_proto_rawDescOnce.Do(func() {
		file_api_protobuf_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_generator_proto_rawDescData)
	})
	return file_api_protobuf_generator_proto_rawDescData
}

var file_api_protobuf_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_protobuf_generator_proto_goTypes = []interface{}{
	(*Run)(nil),                            // 0: generator.v1.Run
	(*Run_Request)(nil),                    // 1: generator.v1.Run.Request
	(*Run_Response)(nil),                   // 2: generator.v1.Run.Response
	(*Run_Request_Options)(nil),            // 3: generator.v1.Run.Request.Options
	(*Run_Request_Values)(nil),             // 4: generator.v1.Run.Request.Values
	(*Run_Request_Values_Golang)(nil),      // 5: generator.v1.Run.Request.Values.Golang
	(*Run_Request_Values_Application)(nil), // 6: generator.v1.Run.Request.Values.Application
}
var file_api_protobuf_generator_proto_depIdxs = []int32{
	3, // 0: generator.v1.Run.Request.options:type_name -> generator.v1.Run.Request.Options
	4, // 1: generator.v1.Run.Request.values:type_name -> generator.v1.Run.Request.Values
	5, // 2: generator.v1.Run.Request.Values.golang:type_name -> generator.v1.Run.Request.Values.Golang
	6, // 3: generator.v1.Run.Request.Values.application:type_name -> generator.v1.Run.Request.Values.Application
	1, // 4: generator.v1.Generator.Run:input_type -> generator.v1.Run.Request
	2, // 5: generator.v1.Generator.Run:output_type -> generator.v1.Run.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_protobuf_generator_proto_init() }
func file_api_protobuf_generator_proto_init() {
	if File_api_protobuf_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_generator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Request_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Request_Values); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Request_Values_Golang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_generator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Run_Request_Values_Application); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_generator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_generator_proto_goTypes,
		DependencyIndexes: file_api_protobuf_generator_proto_depIdxs,
		MessageInfos:      file_api_protobuf_generator_proto_msgTypes,
	}.Build()
	File_api_protobuf_generator_proto = out.File
	file_api_protobuf_generator_proto_rawDesc = nil
	file_api_protobuf_generator_proto_goTypes = nil
	file_api_protobuf_generator_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratorClient interface {
	Run(ctx context.Context, in *Run_Request, opts ...grpc.CallOption) (*Run_Response, error)
}

type generatorClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorClient(cc grpc.ClientConnInterface) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Run(ctx context.Context, in *Run_Request, opts ...grpc.CallOption) (*Run_Response, error) {
	out := new(Run_Response)
	err := c.cc.Invoke(ctx, "/generator.v1.Generator/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
type GeneratorServer interface {
	Run(context.Context, *Run_Request) (*Run_Response, error)
}

// UnimplementedGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedGeneratorServer struct {
}

func (*UnimplementedGeneratorServer) Run(context.Context, *Run_Request) (*Run_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Run_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generator.v1.Generator/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).Run(ctx, req.(*Run_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generator.v1.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Generator_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf/generator.proto",
}
