name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: make cleanup
      - name: Generate wire
        run: make wire
      - name: Vendor
        run: make vendor
      - name: Test
        run: make test
      - name: Lint
        run: make lint
      - name: Send code coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
